apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}

data:
  user: {{ .Values.env.username | b64enc }}
  password: {{ .Values.env.password | b64enc }}
  host: {{ .Values.env.host | b64enc }}